name: devtel
version: 0.0.1

# TODO: Add more hooks
# TODO: Add common properties (like the ones we are sending for CLI)
# TODO: Figure out versioning, deployment, and downloading releases.
# TODO: Delete old log files
# TODO: Move tracker creation to the main and pass it into cmd

hooks:
  - event: before:build
    baseArgs: ["--skip-update", "track"]
  - event: after:build
    baseArgs: ["--skip-update", "track"]
  - event: before:deploy
    baseArgs: ["--skip-update", "track"]
  - event: after:deploy
    baseArgs: ["--skip-update", "track"]

binaries:
  - os: darwin
    arch: amd64
    # can be either an URL or local path
    path: ./bin/devtel
  - os: darwin
    arch: arm64
    # can be either an URL or local path
    path: ./bin/devtel
