name: devtel
reportingTeam: fnd-dtss
description: Devspace telemetry plugin
oss: true
slack: dev-tooling-notifications
library: true
commands:
  - devtel
circleAPIKey: 2b5e5793e375e5a6ddf98251848372496e943192
lintroller: platinum
releaseType: semver
releaseOptions:
  allowPrereleases: true
  allowMajorVersions: true
deployTo:
  environments: []
arguments:
  circleAPIKey: 2b5e5793e375e5a6ddf98251848372496e943192
  commands:
    - devtel
  dependencies:
    optional: []
    required: []
  description: Devspace telemetry plugin
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  opslevel:
    confluenceSpaceKey: DTSS
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: true
  reportingTeam: fnd-dtss
  type:
    - library
  vaultSecrets: []
modules:
  - name: github.com/getoutreach/stencil-base
    version: v0.2.1-rc.1
  - name: github.com/getoutreach/stencil-golang
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: DTSS
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
