name: devtel
reportingTeam: fnd-dtss
description: Devspace telemetry plugin
slack: dev-tooling-notifications
library: true
commands:
  - devtel
circleAPIKey: ""
lintroller: platinum
releaseType: semver
releaseOptions:
  allowPrereleases: true
  allowMajorVersions: true
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  commands:
    - devtel
  dependencies:
    optional: []
    required: []
  description: Devspace telemetry plugin
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  opslevel:
    confluenceSpaceKey: DTSS
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: false
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: true
  reportingTeam: fnd-dtss
  type:
    - library
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-base
    version: v0.2.1-rc.1
  - name: github.com/getoutreach/stencil-golang
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: DTSS
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
